### ISSUE TITLE
Problems to install

### ISSUE THREAD

**Issue by LuisDomingo** [nutriverse/intergrowth#41]
Got this message when installing:

Downloading GitHub repo nutriverse/intergrowth@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/nutriverse/intergrowth/tarball/HEAD' failed

Thanks for your help.

**Comment by ernestguevarra** [comment]
hi @LuisDomingo thanks for your message here.

I am not completely sure why this is happening. I just tried installing it now and it works. From the error message it seems like it might be a downloading issue? Maybe internet?

Are you able to tell me more about what your system is (operating software)? If you are using Windows, you might need the `Rtools` software installed to install from GitHub in R.

Let me know also what your R version is.

Thanks. We'll sort this out.

**Comment by LuisDomingo** [comment]
Hi, my operating system is linux (Debian 11), running R 4.2.2 over RStudio 2022.12.0 Build 353.

By the way, I tried to install in posit.cloud/ (RStudio Pro 2022.12.0 Build 353.pro20), R 4.2.2, and it successfully did. So, it could be something on my pc.

**Comment by LuisDomingo** [comment]
It looks like the problem was the internet. So, I got the package from the API <https://api.github.com/repos/nutriverse/intergrowth/tarball/HEAD> and manually installed. Ready to explore it.

Thanks so much @ernestguevarra !!!

**Comment by ernestguevarra** [comment]
Do give me feedback. This is a work in progress. I am not fully happy with how I implemented some of the API. Also, there are a lot more from the Intergrowth work that I haven't added here. So, very much a work in progress.
